### ISSUE TITLE
Wiiu builds fail to load assets and Overlays

### ISSUE THREAD

**Issue by ruijtunes** [libretro/beetle-supergrafx-libretro#118]
These core worked perfectly until the changes made on the 2nd of October.

Commits on Oct 2, 2021
Remove unused file
@twinaphex
twinaphex committed on 2 Oct

slim down on zlib
@twinaphex
twinaphex committed on 2 Oct

The problem has to be with these changes.

**Comment by Ploggy** [comment]
Happens to me too, I manually updated assets just to be sure..
![20211124_112823](https://user-images.githubusercontent.com/1160255/143232544-420f805d-dce4-4b7c-8791-3e692705c5be.jpg)
