### ISSUE TITLE
ACCURATE?

### ISSUE THREAD

**Issue by Eggo-dotcom** [libretro/beetle-supergrafx-libretro#126]
This core is PCE fast with sgx support if I understand correct.

Is it possible to get an Accurate mode release as well or add it as an option?

There is an accurate core but unlike this core it is outdated (seems abandoned) This core is up to date so Im asking in case somone would be ok doing it.

Thanks,

**Comment by hizzlekizzle** [comment]
This is indeed based on the fast core, but I'm pretty sure the 'accurate' core is newer than this one.

**Comment by Eggo-dotcom** [comment]
This is based on mednafen 1.29 the accurate one hasnt been updated since 0.9.48 and that core has bugs that canbe reproduced which are not present here 1.29

**Comment by Eggo-dotcom** [comment]
> This is indeed based on the fast core, but I'm pretty sure the 'accurate' core is newer than this one.

all this is ok here and bad with the other old accurate core 
[changes.txt](https://github.com/libretro/beetle-supergrafx-libretro/files/8041699/changes.txt)

**Comment by negativeExponent** [comment]
i believe this is not a report or issue related to this core...

**Comment by Eggo-dotcom** [comment]
> i believe this is not a report or issue related to this core...

Its a feature request

**Comment by negativeExponent** [comment]
not really

**Comment by Eggo-dotcom** [comment]
Ok. Please add ability to toggle to accurate mode.

**Comment by negativeExponent** [comment]
> Ok. Please add ability to toggle to accurate mode.

wow.. its that easy? THEN DO IT YOURSELF

**Comment by Eggo-dotcom** [comment]
> > Ok. Please add ability to toggle to accurate mode.
> 
> wow.. its that easy? THEN DO IT YOURSELF

I dont know if its that easy, but i already found a solution. Have been using mednafen proper with mednaffe front end no longer care for a ported core

**Comment by negativeExponent** [comment]
users like you gives retroarch a bad reputation

**Comment by Eggo-dotcom** [comment]
I think retroarch is awesome. How do i affect its rep? I simply found a core with a problem and came for help. Its one core. It doesnt define retroarch. Im sorry if i made anything bad.
