### ISSUE TITLE
CD Images with ISO MODE1/2048 tracks support broken

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/beetle-supergrafx-libretro#13]
Can't launch any CD games that are working fine with PCE-Fast, got:

RetroArch [libretro ERROR] :: Uncorrectable data at sector 3590
CC Error: 03 11 05

Everything worked fine on a Supergrafx fork from April.
Something happened with the CD-Rom code Update?

**Comment by Awakened0** [comment]
I tried launching a CD game with this core and my monitor went black for a second. Then it "crashed" back to XMB and when I quit RetroArch I was hard locked to a black screen and had to power off and back on :/

**Comment by Awakened0** [comment]
I realized I forgot to set the same system dir I use for PCE_Fast for this core when I tried it. The crash was because of the missing BIOS. I can launch all of my CD games with the latest build of this core now and they all seem to play the same as they do in Fast. My images are bin/cue or iso/cue (no extra audio files). Not sure why you're having a problem @Tatsuya79; I'm on Windows 10 in case this is a platform specific issue.

**Comment by Tatsuya79** [comment]
It launches the bios, that's when I press "start" that I get this Uncorrectable data error.
I'm on win7 x64, all my games are cue+bin with external ogg that are working on PCE_Fast / SGX before the CD-ROM code Update.

**Comment by Awakened0** [comment]
Hmm, IDK what's up then. It'd probably be best to test a redump verified image.

**Comment by Tatsuya79** [comment]
That's strange I see that Error on the OSD, the cmd.exe prompt spams it non stop but my debug log shows nothing at all.

I use `retroarch_debug.exe --menu --verbose --log-file log.txt 2>&1` 
logging is on 0 debug.

**Comment by Awakened0** [comment]
I checked my log (ran from a command prompt with verbose enabled in my cfg, and copied it into Notepad++) and didn't see that error anywhere.

**Comment by Tatsuya79** [comment]
Same problem "Uncorrectable sectors" shown by the OSD on Android.

**Comment by Tatsuya79** [comment]
I grabbed a Redump image (cue+bin) and it's working.
Trying to understand why, I see data tracks are MODE1/2352 while my images are all MODE1/2048.
I converted Adams Family (a game with no sound track) from 2048 to 2352 and it's now working fine.

Is MODE1/2048 not working at all?

**Comment by retro-wertz** [comment]
just to add this info.... CHD images that were made based on mode1/2048 will also fail to load.

**Comment by Tatsuya79** [comment]
Fixed with #43 
Thanks. :)
