### ISSUE TITLE
6-button gamepad + multitap issue

### ISSUE THREAD

**Issue by negativeExponent** [libretro/beetle-supergrafx-libretro#132]
> what is exactly the issue on "supergrafx/pce_fast" that we had to do this modifications (if needed?)

>Basically in these 2 games I'm testing:

>* Street Fighter II': 6-buttons work fine with multitap, if it's OFF however for some reason P2 is still active and P1 controls BOTH P1 and P2, making impossible to play solo pretty much.
>* Garou Densetsu Special: 6-buttons is shifted with multitap, making some buttons useless or doing other button action (e.g. VI acts as RUN, III acts as I) and it can cause freezes/crashes/glitches. With multitap OFF P2 is still active and P1 controls P2.

>Only PCE and SuperGrafx cores are affected, both games run fine with 6-buttons with PCE Fast core (because that one doesn't have a multitap toggle option I guess).

_Originally posted by @bslenul in https://github.com/libretro/RetroArch/issues/15251#issuecomment-1539872081_

**Comment by anzz1** [comment]
Which one of the 5 games released for SuperGrafx uses 6 buttons?
Those games mentioned in the comment you quoted are for the PCE, not SGX.

**Comment by negativeExponent** [comment]
this issue should be fixed... unless its not...
