### ISSUE TITLE
Port CHD Support From PCE-Fast

### ISSUE THREAD

**Issue by Awakened0** [libretro/beetle-supergrafx-libretro#22]
CHD support was recently added to the PCE-Fast core. Since this core is very similar it shouldn't be hard to port over.

**Comment by Tatsuya79** [comment]
I wouldn't be too sure about that.
The cd-rom code is different and doesn't work at all for me on win7 x64.

**Comment by Awakened0** [comment]
@rtissera figured it'd be a simple copy paste, but I forgot about your issues and the different CD-ROM code. I still don't have any issues loading CD games on Win10 with this core.

**Comment by rtissera** [comment]
PR https://github.com/libretro/beetle-supergrafx-libretro/pull/24 should do it.

**Comment by Awakened0** [comment]
Built myself and tested the same CHD's I did in the PCE_Fast core; everything looks good. Thanks!
