### ISSUE TITLE
How diffrent is this repo from beetle-pce-fast-libretro?

### ISSUE THREAD

**Issue by cecton** [libretro/beetle-supergrafx-libretro#50]
I've been using this core for some time to play PCE, PCE CD-ROM and SuperGrafx games without any trouble.

I know Mednafen pretty well and I'm positive that there are 2 modules: pce and pce-fast. This repository and https://github.com/libretro/beetle-pce-fast-libretro seems to use pce-fast.

So I'm wondering: what are the differences between this core and the other? Are they diverging over time?

**Comment by retro-wertz** [comment]
this core is based on mednafen's pce_fast. the difference is that this core is able to play supergrafx games aside from the pce roms. from my understanding, this core and the pce_fast that plays only pce roms has been separate so that pce_fast core can be optimized to run in more devices.

**Comment by cecton** [comment]
Thanks! Do you know if there is a list of known devices where it's known to work? I'm maintaining the user packet for Arch Linux for this repo only. It seems it works on RPI1 (haven't really tested, but it compiles) & 2.

**Comment by retro-wertz** [comment]
no i dont have list of supported system this core has. other than pce_fast core is optimized to run only pce_roms this core should be similar.

performance wise its nice to hear this core runs fine on RP1. have you tried running SGX games like 1941, aldynes, battle ace, madou king granzort and especially dai-makaimura(ghost and goblins)? running in tru supergrafx mode is a bit demanding....

**Comment by cecton** [comment]
No I mean I'm just compiling it. I'm only testing on a Rpi2 and it runs smoothly with Daimakaimura which is a Supergrafx game. I don't see much reason to use the other `pce_fast` though... unless i could really benchmark it but I'm not experienced with that.

**Comment by cecton** [comment]
I have this tab opened since 27 December 2017 (I keep a lot of tabs). I'm now closing it since I got an answer. Thanks a lot

> the difference is that this core is able to play supergrafx games aside from the pce roms. from my understanding, this core and the pce_fast that plays only pce roms has been separate so that pce_fast core can be optimized to run in more devices.
