### ISSUE TITLE
Arcade Card RAM is not always serialized

### ISSUE THREAD

**Issue by FrozenFish24** [libretro/beetle-supergrafx-libretro#67]
The emulator determines Arcade Card RAM is being used (and therefore starts serializing it) on-the-fly when it is first written to by the emulated software. This means save states can increase in size over the course of emulation which is forbidden by the Libretro API and Run Ahead will fail for Arcade Card titles during the transition from BIOS to in-game as discussed in [this issue](https://github.com/libretro/RetroArch/issues/6849).

A simple fix is to force the `ACRAMUsed` boolean in `arcade_card.h/cpp` always True so ACRAM is always included in serialization. However this will increase the size of save states on disk for all CD games regardless of whether they touch ACRAM or not.

Another option is to force `ACRAMUsed` to True only for the first serialization. This will allow the front end's buffer to be sized large enough, but subsequent states can still be smaller and in practice this will be within a `retro_serialize_size` call and discarded anyway. This would avoid increased save state size on disk and allow Run Ahead to function properly.

**Comment by Tatsuya79** [comment]
2543KB vs 406KB if I compare a state with arcade card (Sapphire) or without (Spriggan).
Better not force it all the time if possible.

**Comment by retro-wertz** [comment]
libretro's size check is a sanity check anyway. supergrafx at least is not using "serialize_size" variable or using the return from retro_serialize_size() was first called, so you can load/save state whenever in an arcade-enabled game (at least on Strider)

tested this in linux and save/load state between when ACRAMUsed is true or false(usually in bios) and runahead (1 frame at least) also works (there is a message at start of core but its too quick to read and too lazy to adjust font size or whatever and nothing about it is shown in log)

dunno during netplay though if it will just use the first returned size from calling serializem which would be around 400K compared to 2.5M

**Comment by Tatsuya79** [comment]
The message is something like "State loading failed. Run Ahead has been disabled." and then run ahead is forced to off.

Explanation from the referenced issue above written by FrozenFish24:
```
I've been able to replicate your issue with Beetle-SGX. 
It seems to be the transition from BIOS to game that's breaking runahead. 
If you wait until you're in-game before enabling it everything works correctly.

Also interestingly, if you then restart (without closing content) runahead survives going BIOS to in-game.
```

**Comment by retro-wertz** [comment]
> The message is something like "State loading failed. Run Ahead has been disabled." and then run ahead is forced to off.
> 
> Explanation from the referenced issue above written by FrozenFish24:
> 
> ```
> I've been able to replicate your issue with Beetle-SGX. 
> It seems to be the transition from BIOS to game that's breaking runahead. 
> If you wait until you're in-game before enabling it everything works correctly.
> 
> Also interestingly, if you then restart (without closing content) runahead survives going BIOS to in-game.
> ```

you know you can enable runahead anytime.. right?
