### ISSUE TITLE
[Regression] Crash dump on the Wii, when loading a second game.

### ISSUE THREAD

**Issue by Cee123** [libretro/beetle-supergrafx-libretro#91]
For some reason the core can only load one game. But if you try and load a second game (with or without closing content) it crash dumps.

**Comment by negativeExponent** [comment]
i question (for now). is this loading a hucard game or cd game. and is it still happening on latest commit.

**Comment by Cee123** [comment]
> i question (for now). is this loading a hucard game or cd game. and is it still happening on latest commit.

Oops sorry about that. Yeah this core doesn't crash anymore. It was back in February when i opened this. Sorry about that. I forgot that i had this open. Doesnt seem to be any issues with it now, it's all working fine.

**Comment by negativeExponent** [comment]
good to hear...
